### ISSUE TITLE
Migration request from IBusConfig to GSettings

### ISSUE THREAD

**Issue by fujiwarat** [vn-input/ibus-unikey#12]
I'm the maintainer of IBus.
ibus-unikey uses IBusConfig and I'd ask to migrate it to GSettings and delete IBusConfig.

E.g. setup/config_utils.cpp
```
void read_config(void *data, UnikeyMainSetupOptions* opt)
{
    GSettings *settings_inputmethod = g_settings_new ("org.freedesktop.ibus.engine.unikey");
    if (ibus_unikey_config_get_string (settings, CONFIG_INPUTMETHOD, &str)) {
    }


...

goolean ibus_uinkey_config_get_string (GSettings *settings,
                                                                const gchar *key,
                                                                gchar** result)
{
    GVariant *value = NULL;
    value = g_settings_get_value (settings, key);
    if (value) {
        *result = g_variant_dup_string (value, NULL);
        g_variant_unref (value);
        return true;
    }
    return false;
}
```

https://groups.google.com/forum/#!topic/ibus-devel/Mu1IoFX-bKE

**Comment by mrlequoctuan** [comment]
Thank you, I will do it when have free time
Maybe this weekend :)

**Comment by fujiwarat** [comment]
Thank you!

**Comment by fujiwarat** [comment]
Do you have any updates?

**Comment by mrlequoctuan** [comment]
I will try to do it soon, do you have any schedule for the next version?

**Comment by fujiwarat** [comment]
I have the plan to release 1.6 after the major IMEs migrate to GSettings.
The current status is here:
https://github.com/ibus/ibus/wiki/GSettingsMigration
Some important IMEs do finish the migration yet.

I don't think the status of ibus-unikey prevents ibus 1.6 but it would be great if you could migrate and I'd ask the current status.

**Comment by mrlequoctuan** [comment]
Currently, I had done it (locally), you can consider this issue is closed
Now, I just want to refactor/change a lot of things (the code is ten years ago)
So it will take a little time to release new version

**Comment by fujiwarat** [comment]
Thank you. I'd like to see the changes. Currently setup/dlg_main_setup.cpp uses IBusConfig at least in git master.

**Comment by fujiwarat** [comment]
Thank you.
https://github.com/vn-input/ibus-unikey/commit/04e7c918c08dd8c8fd2037b474b241646ac8027f
