### ISSUE TITLE
Cần người tiếp tục phát triển & bảo trì dự án

### ISSUE THREAD

**Issue by mrlequoctuan** [vn-input/ibus-unikey#14]
Chào mọi người,

Thời gian qua, vì lý do công việc cũng như cuộc sống, mình đã không thể tiếp tục phát triển, bảo trì, cũng như hỗ trợ cho dự án này.

Mình cũng thấy hiện tại có rất nhiều bản fork được tạo ra, nhưng cũng không có nhiều thời gian để xem xét.

Vì vậy mình tạo issue này để mọi người có thể góp ý về tương lai, cũng như adopt như án này, hoặc chỉ đơn giản là review các pull requests.

Xin cảm ơn!

**Comment by shockvalueii** [comment]
Hi Quân, bạn có thể cho mình biết những gì cần làm cho dự án này được không?

**Comment by nguyenphivn** [comment]
Mình cũng có thời gian rãnh cũng có thể đọc code được nhưng chưa có kinh nghiệm maintain và hiểu rõ code của bộ gõ lắm nếu được nhờ bạn hướng dẫn và pass lại dự án này. 

Bên cạnh mình sẽ kiêu gọi cộng đồng nhờ giúp đỡ.

**Comment by ZarHar** [comment]
Bạn hướng dẫn qua bộ gõ được không? Mình sẽ cố gắng maintain với dev bộ gõ này.

**Comment by ducy23061999** [comment]
Em cũng k làm được gì nhiều nhưng sẽ rán kêu gọi cộng động ạ

**Comment by vietdien2005** [comment]
- Em đang rất quan tâm đến dự án này, và rất mong muốn được tham gia đóng góp
- Hiện tại em chưa nắm bắt nhiều về code của dự án, liệu anh có thể viết tài liệu hướng dẫn không ? :grin: :grin:

**Comment by canhkieu** [comment]
Trước đây cũng đã thử kéo về nhưng ngặt nỗi thư viện và cũng kô hiểu về dự án nên lại đắp chiếu. Quân có thể viết một chút hướng dẫn mở đầu cách build, cấu trúc thư mục, những file quan trọng. Cộng đồng lập trình VN cũng rất mạnh, chỉ có kô biết làm mới kô làm được, nếu có hướng dẫn, chắc chắn ibus-unikey sẽ phát triển

**Comment by TKNgu** [comment]
Hi tác giả có thể giới thiệu qua về công nghệ sử dụng và kiến trúc hay triết lý thiết kế code được không ?

**Comment by louisnguyen1012** [comment]
Trên fork này có thêm ít thông tin để tiếp cận bộ gõ này: https://github.com/quanghgx/ibus-unikey

**Comment by windlight9x** [comment]
En chào anh ạ!

Nếu em muốn nhận dự án này thì sẽ bảo trì và phát triển như thế nào ạ, sẽ fork ra bản mới hay tiếp quản từ anh ạ!

**Comment by nguyenphivn** [comment]
https://github.com/quanghgx/ibus-unikey

https://github.com/bongnv/ibus-unikey

có cách nào để liên hệ tác giả của 2 bản fork này không mọi người?

**Comment by TKNgu** [comment]
Hi all.
Theo mình đây không phải là một dự án quá lớn và yêu cầu trước măt là bảo trì và sửa lỗi. Vậy nên một nhóm 3-5 người là có thể bắt đâu ngay. 
1. Cần tìm người lãnh đạo dự án yêu cầu chính là có tính thần còn các vấn đề công nghệ có thể tìm hiểu thêm.
2.  Tuyển thành viên.
3. Trao đổi về các vấn đề cần giải quyết.

P/S Bạn nguyenphivn có thể ? Mình không có nhiều thời gian lắm.

**Comment by nguyenphivn** [comment]
Mình có tạo một slack channel để cùng thảo luận, bạn nào quan tâm mình cùng bàn nhé: 

[https://join.slack.com/t/ibus-unikey/shared_invite/enQtMzUxNzEzNjg0MzQyLWM4NjdiNWE5YzIyOTZhNjU0MmI5OWYxOWMzYWVlNTZhM2Q0MTM5YWI0ZDU5MzAzODMxZjg2OTU4MWM3ZDI5ZmI](https://ibus-unikey.slack.com/)

**Comment by TKNgu** [comment]
Sao không vào được nhỉ ?

**Comment by nguyenphivn** [comment]
vừa chỉnh lại, đã ok rồi đấy bạn

**Comment by thehung** [comment]
Bọn mình đang xin kinh phí cho một dự án nguồn mở, có thể tài trợ một chút ngân sách để đợt tới nhóm nào nhận phát triển có thêm động lực để làm việc! Cộng đồng đang rất cần hoàn thiện bộ gõ tiếng Việt trên linux, các bộ gõ hiện tại nhiều lỗi quá!

**Comment by Kartist98** [comment]
mình 0 biết gì về dev, nhưng mờ sẽ kiu gọi dân chúng tham gia :v

**Comment by Kartist98** [comment]
@thehung nếu phát triển tiếp ibus-bogo thì sao nhỉ?

**Comment by hoainam10th123** [comment]
Mình từng build source gparted (GTK++) bằng code block trên Ubuntu. Nếu tác giả cung cấp được ý tưởng giải thuật của project thì mình xin 1 chân tham gia.

**Comment by minhkhoa2000** [comment]
Tuyệt vờiii

**Comment by lacoski** [comment]
Em còn là sinh viên, rất mong được đóng góp cho dự án😃

**Comment by lewtds** [comment]
Mình thấy dự án này hoạt động ổn 98% (ít nhất là có thể nhận phím gõ, convert ra tiếng Việt và update text trên màn hình một cách ổn định thông qua cơ chế preedit). Các vấn đề mà người dùng hay complain là:

- Thường xuyên crash (trước đây mình có nói chuyện với anh Tuấn maintainer của Fedora thì anh có nói nhận email tự động báo lỗi liên tục, mình đoán chủ yếu là do tính năng mouse tracking). Cái này có thể giải quyết bằng cách thường xuyên sử dụng các công cụ phân tích code dự báo lỗi (như https://clang-analyzer.llvm.org/ và valgrind) công với viết test và chạy test tự động. Viết end-to-end integration test kiểu tạo máy ảo, cài ibus-unikey, cài các phần mềm để gõ như gedit, sau đó dùng phần mềm UI automation (VD như dogtail) giả lập thao tác người dùng gõ văn bản rồi assert kết quả ra đúng như mong muốn, không bị lỗi hay crash (thêm CircleCI integration với GitHub luôn là ngon). Có thể xem qua dự án bogo: https://github.com/lewtds/bogo/blob/master/tests/gui.py

- Preedit khó chịu. Có thể dùng option của IBus để không hiện dấu gạch chân với preedit nhưng không phải ứng dụng/toolkit nào cũng hỗ trợ (khoảng 70-80%). Mình thấy cũng good enough. Nhìn mấy bộ gõ trên Android có vẻ đều dùng preedit và tắt gạch chân nhưng bên đó hỗ trợ đồng đều hơn nên không dễ nhận ra. Với các edge case thì có thể nói chuyện với maintainer của các phần mềm có vấn đề đó để giúp họ implement tính năng tắt gạch chân (mình rất recommend cái này vì trước đây cá nhân mình đã học được rất nhiều về cách làm việc nhóm và kỹ năng giao tiếp bằng tiếng Anh với người nước ngoài qua email/chat hồi mình implement tính năng edit surrounding text cho Qt5 và GNOME Terminal, mọi người trên kênh #ibus ở Freenode IRC cũng rất thân thiện).

Sau khi xử lý những cái trên rồi thì mình nghĩ nên tập trung vào một distro chính (Ubuntu chẳng hạn) và cải thiện trải nghiệm ban đầu của người dùng. VD như cài ibus-unikey phải qua bao nhiêu bước? có giảm bớt được không? có cần manual setup sau khi cài không? Theo lời Steve Jobs thì "it [should] just work" ; )

Vài lời cảm nghĩ vậy thôi. Chúc các bạn đạt được những dự định mình đặt ra và học được nhiều điều mới.

**Comment by anhhuynhnhat** [comment]
Hy vọng là mình cũng có thể giúp sức cho bạn, bên Fefora thì mình thấy họ đã hoàn thiện khá tốt cho bộ gõ của họ, mình nghĩ tập trung cho debian, loại bỏ 1 số cái như gạch chân,.... là ổn

**Comment by mrlequoctuan** [comment]
Mình cũng không biết cần làm gì trước, có một số việc là
- Giải quyết các issue đang Open, như  #12
- Xem xét một số bản fork, một số cải tiến có thể merge vào (cần test)
- Thật ra code này mình viết rất lởm, nếu viết lại được thì tốt =))
   - Chuyển qua dùng cmake cho dễ build
   - Có thể chuyến code sang python (trừ phần ukengine)
- Viết automation test như @lewtds đề xuất
- Viết hướng dẫn và giải đáp thắc mắc

Về cách build thì nó "đơn giản" như mấy soft khác trên linux thui
Tài liệu có thể tham khảo từ đây https://github.com/ibus/ibus/wiki/Develop

Về cách làm việc thì có thể tham khảo các dự án open-source khác thôi
- Tạo issue (feature, bug) nếu chưa có
- Tạo merge request
- Mọi người review nếu ok thì accept

**Comment by mrlequoctuan** [comment]
@hoainam10th123 các ime điều gọi qua thư viện của ibus, không có gọi trực tiếp đến các thư viện GUI
Trong source có gọi đến X11, thật ra đây là hack/trick, cũng không nên dùng lắm

**Comment by Kartist98** [comment]
cái cần thiết nhất bây giờ là gõ tiếng Việt trên snapp app, snap app ngày càng nhiều, cần dùng nhièu app trong đó mà không gõ được tiếng Việt

**Comment by tommynguyen1995** [comment]
Hi all,
Cho em hỏi tình hình dự án này ra sao rồi ạ? Em cũng muốn tham gia nhưng không join được Slack channel.

**Comment by trung674** [comment]
Mình thấy có 2 forked repo đc update khá thường xuyên

- https://github.com/lzutao/ibus-unikey
- https://github.com/ibus-unikey/ibus-unikey

Mọi người qua đó tham khảo thử xem

**Comment by minhna** [comment]
Mình dùng trên ubuntu 18.04 thì hoạt động cũng ổn. Vấn đề lớn nhất chỉ là không hoạt động với các ứng dụng cài từ snap thôi. Trước mắt sửa được cái này là sống tiếp được mấy năm nữa.

**Comment by Banbeucmas** [comment]
Chạy khá ổn trên Arch. Còn mỗi vấn đề là những ứng dụng như Discord thì không dùng được.

**Comment by ntd252** [comment]
không biết dự án làm đến đâu rồi nhỉ, liệu có nên làm một nhóm FB hay một fanpage để nhiều người biết thông tin và tham gia không?

**Comment by Kartist98** [comment]
vậy giờ sao rồi nhỉ?

**Comment by mrlequoctuan** [comment]
Hiện tại mình đã quyết định dành ít thời gian cuối tuần để làm tiếp rùi
Tạm thời cũng không cần gì nữa

Khi cần mình sẽ tạo issue mới cho từng vấn đề cần giải quyết để ai muốn có thể tham gia
Còn giờ mình sẽ close issue này

Cảm ơn tất cả các bạn đã quan tâm!!!

**Comment by thuandt** [comment]
@mrlequoctuan welcome back :+1:

**Comment by quangndhust** [comment]
Ngày trước mình có cài đặt và sử dụng bộ gõ với HDH Ubuntu 16.04 LTS khi đăng nhập tài khoản mà bật chế độ gõ tiếng việt thì mật khẩu lại nháy và hiển thị, không rõ bạn nào đã từng bị như thế chưa
