### ISSUE TITLE
Snap app implementation

### ISSUE THREAD

**Issue by Banbeucmas** [vn-input/ibus-unikey#15]
https://github.com/vn-input/ibus-unikey/issues/14
Prior to this so I will create my first issue here.

Like title suggests, we need implementation for snap app, election and such  to use ibus-unikey properly with Discord, Atom, etc...

**Comment by dungwinux** [comment]
VSCode (electron-based) vẫn dùng với ibus-unikey được :smiley:

**Comment by Banbeucmas** [comment]
@dungwinux test với Discord xem

**Comment by mrlequoctuan** [comment]
về cơ bản, vấn đề này là giữa ibus với snap, cho nên ibus-unikey không làm gì được bạn nhé

issue này chủ yếu sẽ do bên snap họ tìm cách giải quyết

**Comment by manhnt9** [comment]
Mình đã tìm hiểu vấn đề này, cũng không phải do snap mà là do chính app đó chưa bundle lib ibus input theo để app sử dụng. Vì mỗi app snap có environment riêng không sử dụng env của system và app thường là input tiếng Anh nên có thể họ chưa support ibus để input ngôn ngữ khác (một vấn đề khó cân nhắc là nên ship input framework nào).

**Comment by thanhphu** [comment]
Mình cũng bị vấn để ko gõ được với nhiều snap app chẳng hạn như Slack, câu trả lời là... chuyển qua dùng flatpak 🤣

**Comment by thuandt** [comment]
Vấn đề là ở snap app packaging chứ không phải do input method :)
