### ISSUE TITLE
Không gõ được tiếng việt trong các IDE của Jetbrains, ...

### ISSUE THREAD

**Issue by mduccc** [vn-input/ibus-unikey#16]
Mình không thể gõ tiếng việt trên Android Studio, Pycharm, PhpStorm cũng như SublimeText, Kate,..

**Comment by baonq-me** [comment]
Mình đang dùng ibus-unikey trên Ubuntu 18.04. Với SublimeText thì không gõ được thật nhưng những soft khác thì vẫn gõ được bình thường.

**Comment by mduccc** [comment]
Mình dùng Arch, DE xfce

**Comment by mrlequoctuan** [comment]
về sublimetext thì bạn xem ở đây nhé
https://forum.sublimetext.com/t/input-method-support/5446
Vấn đề này không thuộc về ibus-unikey

**Comment by thanhphu** [comment]
Ubuntu 18.04, Mình gõ được cả CLion, IntelliJ, Android Studio bản mới nhất bình thường, có lẽ lên close issue này :)

**Comment by mduccc** [comment]
> Ubuntu 18.04, Mình gõ được cả CLion, IntelliJ, Android Studio bản mới nhất bình thường, có lẽ lên close issue này :)

Bạn dùng DE nào?

**Comment by thanhphu** [comment]
> > Ubuntu 18.04, Mình gõ được cả CLion, IntelliJ, Android Studio bản mới nhất bình thường, có lẽ lên close issue này :)
> 
> Bạn dùng DE nào?

Mình dùng GNOME

**Comment by mduccc** [comment]
> > > Ubuntu 18.04, Mình gõ được cả CLion, IntelliJ, Android Studio bản mới nhất bình thường, có lẽ lên close issue này :)
> > 
> > 
> > Bạn dùng DE nào?
> 
> Mình dùng GNOME

Mình dùng XFCE

**Comment by tuanit** [comment]
Mình cũng bị tương tự. Tìm hiểu thì thấy bảo các app cài trên snap đều không gõ được tiếng việt. Các nào có cách fix lỗi gõ tiếng việt trên các app cài trên snap thì alo nhé.

**Comment by thanhphu** [comment]
> 
> 
> Mình cũng bị tương tự. Tìm hiểu thì thấy bảo các app cài trên snap đều không gõ được tiếng việt. Các nào có cách fix lỗi gõ tiếng việt trên các app cài trên snap thì alo nhé.

Phải bảo tác giả snap thêm ibus library, không thì dùng flathub thay cho snap thôi bác
