### ISSUE TITLE
Lỗi tính năng gợi ý trên các phần mềm như VSCode, TexMaker

### ISSUE THREAD

**Issue by npthinhdev** [vn-input/ibus-unikey#18]
Có lẽ là do vấn đề của pre-edit nên mấy tính năng gợi ý code nó không được hoạt động tốt. Hy vọng bạn sớm khắc phục được lỗi này. Xin cảm ơn!

**Comment by mrlequoctuan** [comment]
Mình khi code lúc nào cũng phải tắt bộ gõ, kể cả gợi ý từ hoạt động thì code cũng không được trơn tru cho lắm
Và lỗi này gần như không thể fix được

**Comment by panoti** [comment]
@npthinhdev Cái preedit này trên window cũng thua luôn ông ơi. Nếu cài đặt được backspace giả trên ubuntu thì ngon hẳn.

**Comment by npthinhdev** [comment]
@panoti t chuyển qua dùng bamboo luôn rồi :D
