### ISSUE TITLE
License

### ISSUE THREAD

**Issue by congdanhqx** [vn-input/ibus-unikey#20]
The ukengine is released under GPLv2 only.

But ibus-unikey is released under GPLv3+.

This is effectively violated section 6 of GPLv2.
See https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility
and https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

---

Xin lỗi bạn, vì mình đang package `fcitx-unikey` cho Void Linux,
gặp vấn đề về giấy phép nên report bên đó trước rồi copy qua bên này.

Tình hình là ibus-unikey không thể được phát hành với giấy phép GPLv3+
vì UkEngine của pklong chỉ được phát hành với giấy phép GPLv2

**Comment by tuanta** [comment]
> Tình hình là ibus-unikey không thể được phát hành với giấy phép GPLv3+
> vì UkEngine của pklong chỉ được phát hành với giấy phép GPLv2

Lỗi serious thế này mà lâu nay chưa ai để ý nhỉ? :(
@mrlequoctuan check kỹ xem? khả năng phải relicense cả ibus-unikey về GPL v2 rồi.

**Comment by congdanhqx** [comment]
Truong Anh Tuan <notifications@github.com> writes:

> Lỗi serious thế này mà lâu nay chưa ai để ý nhỉ? :(
> @mrlequoctuan check kỹ xem? khả năng phải relicense cả ibus-unikey về GPL v2 rồi.

Có vẻ như mọi người không quen thuộc lắm với việc tương thích lẫn nhau
của các giấy phép.

Mình thì toàn dùng bộ gõ của vim/emacs để gõ tiếng Việt (kể cả khi
cần dùng với firefox) nên không để ý lắm tới chuyện này.

fcitx-unikey _hình như_ là copy code từ ibus-unikey về nên giữ nguyên
GPLv3 như ibus-unikey.
Maintainer của fcitx-unikey (cũng là maintainer của fcitx) không có dùng tiếng Việt.

-- 
Danh

**Comment by mrlequoctuan** [comment]
Cụ thể source ukengine lấy từ x-unikey, license **GNU LIBRARY GENERAL PUBLIC LICENSE Version 2**

```
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.
```

![Screenshot 2019-04-16 at 16 54 28](https://user-images.githubusercontent.com/98257/56200165-73f7dd80-6068-11e9-9cb8-d440dcee51e8.png)

Không biết mình có hiểu sai chỗ nào không nhỉ?

**Comment by mrlequoctuan** [comment]
Vụ này nhớ ngày xưa có bàn rồi, mà không nhớ là từ thời scim-unikey hay ibus-unikey nữa
Raise lên từ bên opensuse hay sao ấy, giờ tìm lại không thấy

**Comment by congdanhqx** [comment]
Lê Quốc Tuấn <notifications@github.com> writes:

> Cụ thể source ukengine lấy từ x-unikey, license **GNU LIBRARY GENERAL PUBLIC LICENSE Version 2**
>
> ```
> This library is free software; you can redistribute it and/or
> modify it under the terms of the GNU Library General Public
> License as published by the Free Software Foundation; either
> version 2 of the License, or (at your option) any later version.
> ```

à, mình chỉ xem file gpl.txt ở thư mục unikey.

Quên không kiểm tra từng file source.

Sorry for the noise.

-- 
Danh
