### ISSUE TITLE
Lỗi khi đang gõ tiếng việt và giữ Shift

### ISSUE THREAD

**Issue by piggybit** [vn-input/ibus-unikey#21]
Hello.
Ví dụ khi mình gõ "dưới đây:" thì khi đang gõ chữ "đây" mình cần thêm dấu ":" thì mỗi khi giữ Shift mình sẽ bị mất tiếng việt.

Gõ trên chrome 79.0.3945.117 mình sẽ bị lỗi này, trên firefox hoặc editor thì không sao :|.

Có workaround là cách rồi lùi lại thêm ":", nhưng gõ nhiều thì rất mất thời gian.
Thanks.

**Comment by hung0913208** [comment]
Bạn có thể giải thích cụ thể các bước để tạo lại lỗi hay không. Bạn có thể confirm lại với latest version của chrome được không

**Comment by thesea2201** [comment]
Mình cũng gặp lỗi tương tự trên `Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)`:
`Input`: `"Hôm nay bạn thế nào?"`
`Output`: `"Hôm nay bạn thế naof?"`
`Version`: `UniKey 4.3 RC5, UniKey 4.3 RC4` trên [trang chủ Unikey](https://www.unikey.org/)
`OS`: `Ubuntu 18.04 LTS 64bit, Gnome 3.28` và `Ubuntu 20.04 LTS 64bit, Gnome 3.36`
Mình đã thử dùng ibus-bamboo theo đề xuất và đã khắc phục được lỗi này.
