### ISSUE TITLE
Is there a reason why 'viqr' input method is not included? 

### ISSUE THREAD

**Issue by phodamentals** [vn-input/ibus-unikey#22]
I would like to use the viqr input method for unikey, versus the standalone viqr-ibus-table.

Why is it not included in the list of input methods?

```
const std::map<const std::string, std::pair<UkInputMethod, const gchar*>> input_method_map {
    { "telex",   { UkTelex,        "Extend Telex" } },
    { "vni",     { UkVni,          "VNI" } },
    { "stelex",  { UkSimpleTelex,  "STelex" } },
    { "stelex2", { UkSimpleTelex2, "STelex 2" } },
};
```

**Comment by tulequ** [comment]
I just want to include popular ones, make it more simple
I don't like fragment

Anyway, you can enable it and maybe with some changes to the way how word is commit

You are the first persion ask for it (more than 10 years from beginning)
