### ISSUE TITLE
Has this been deprecated?

### ISSUE THREAD

**Issue by ameamenoame** [vn-input/ibus-unikey#24]
@tulequ just added a deprecation message in README.md recently. Can I ask for the reasons behind it? It's a great loss as most Vietnamese users who switched to Ubuntu from Windows would likely use ibus-unikey as it's officially included in GNOME's Language Support.

**Comment by tulequ** [comment]
There are two things:
- There are a lot of reported bug. I don't have much freetime for this now (and also future)
- Some new Vietnamese input project maybe better (feature & support)
  - I think we should add it to origin ubuntu repo, so user will have more options

I really don't want to deprecation it, but I can not found any volunteer for this project now
I just thinking what about @fujiwarat, do you have any idea? like moving this to **ibus**

Recently I release version 0.7 beta1, I think it ready for production now
That release **not include deprecation message**

I see https://bugs.launchpad.net/bugs/1872319, but I not read clearly yet

**Comment by tulequ** [comment]
I just check mail and see https://mentors.debian.net//package/ibus-unikey
I think @gunnarhj should use version 0.7, not git version for now
Or I can make it as an official release

**Comment by gunnarhj** [comment]
> - Some new Vietnamese input project maybe better (feature & support)
> - I think we should add it to origin ubuntu repo, so user will have more options

That's possible, but getting new projects in Debian/Ubuntu is more work administratively.

> I just thinking what about @fujiwarat, do you have any idea? like moving this to ibus

He is professional and helpful, but I have no idea if he would be willing to take this on.

>  think @gunnarhj should use version 0.7, not git version for now
> Or I can make it as an official release

It would be great - and preferable - if you could make an official release. Then I would use that.

**Comment by gunnarhj** [comment]
@tulequ: Hmm.. I see now that 0.7.0-beta1 includes everything except those latest README.md changes. So you are right, I should use that instead. No need for an extra release.

**Comment by gunnarhj** [comment]
@tulequ: I changed to 0.7.0+beta1 at https://mentors.debian.net//package/ibus-unikey .

**Comment by fujiwarat** [comment]
Sorry, I don't know about which problem you're talking.
But I don't touch Debian and I'm fine with the github repository for Fedora.

**Comment by ameamenoame** [comment]
> Some new Vietnamese input project maybe better (feature & support)
I think we should add it to origin ubuntu repo, so user will have more options

@tulequ The main problem with this is that, as you and I both know, Unikey is **the** default choice for every Vietnamese wanting to type Vietnamese on their computer. When I started using Linux, one of first things I searched for was Unikey whether it be fcitx-unikey or ibus-unikey; I didn't even know there were alternatives like ibus-bamboo before I visited this repository. Deprecating such a relatively widespread tool is devastating.

Of course, we're not forcing you to keep maintaining this when you've done just so for the past 8 years. You deserve a break from this.

I think moving forward, the solution can be replacing ibus-unikey with ibus-bamboo as the Vietnamese input source in GNOME's Language Support on Ubuntu. What do you think @gunnarhj?

**Comment by gunnarhj** [comment]
@fujiwarat: I think the question to you was if you possibly have any idea how to find a new maintainer for the [ibus-unikey project](https://github.com/vn-input/ibus-unikey).

@tghgg: I see that ibus-bamboo [is already in a PPA](https://launchpad.net/~bamboo-engine/+archive/ubuntu/ibus-bamboo). I think a natural step would be to ask the ibus-bamboo maintainer if he is interested in including it in Debian/Ubuntu officially.

@tulequ: What do you know about [this forked ibus-unikey project](https://github.com/ibus-unikey/ibus-unikey)? Is it properly maintained? Would it be a worthy replacement for your project in Debian/Ubuntu?

In any case I can tell that ibus-unikey 0.7.0~beta1 is on its way into Debian unstable and later to Ubuntu 20.10.

**Comment by tulequ** [comment]
@fujiwarat ok, you can ignore this ^^!

@gunnarhj I don't know which fork is good enough
If there a important (small) bug, I will continue to fix it
So, just keep use this repository until we know a better fork

**Comment by gunnarhj** [comment]
@tulequ wrote:
> I don't know which fork is good enough

Ok, noticed.

> If there a important (small) bug, I will continue to fix it

That brings relief, indeed. An appreciated answer to the question asked in the title of this thread. :)

> So, just keep use this repository until we know a better fork

Will do.

I have a question as regards the maintenance of the Debian package. The maintainer of most input related Debian packages is the Debian Input Method Team. I can think it would be wise to make that team the maintainer of `ibus-unikey` as well. That way others more naturally can help with the mostly administrative job to keep the package in good shape, while you can focus on the functionality. Would you mind if I propose that change? If not, I would suggest that you are added to the "Uploaders" field, so you as a co-maintainer still have the option to upload changes yourself without calling it a "non-maintainer upload".

**Comment by tulequ** [comment]
>I have a question as regards the maintenance of the Debian package. The maintainer of most input related Debian packages is the Debian Input Method Team. I can think it would be wise to make that team the maintainer of ibus-unikey as well. That way others more naturally can help with the mostly administrative job to keep the package in good shape, while you can focus on the functionality. Would you mind if I propose that change? If not, I would suggest that you are added to the "Uploaders" field, so you as a co-maintainer still have the option to upload changes yourself without calling it a "non-maintainer upload".

I don't want to do it anymore. I am exhausted

**Comment by gunnarhj** [comment]
@tulequ: Does that mean we have your consent to make the suggested change? Please note that my suggestion means that you would be _liberated from the work with and responsibility for_ the Debian side of the project.
