### ISSUE TITLE
Tác giả có còn support bộ gõ này không vậy?

### ISSUE THREAD

**Issue by zenfas** [vn-input/ibus-unikey#30]
Đây là bộ gõ tiếng Việt tốt mình đã được dùng. Hiện nó được hầu hết các distro đưa vào repo chính thức, thật đáng tiếc nếu nó không còn được bảo trì và update :(
Mình sẵn sàng donate 1 ít nếu các dev tiếp tục bảo trì và fix lỗi

**Comment by tulequ** [comment]
Mình không có thời gian nên hiện tại mình không còn support nữa bạn ạ
