### ISSUE TITLE
Lỗi không gõ được từ "huơ" "khuơ"

### ISSUE THREAD

**Issue by zenfas** [vn-input/ibus-unikey#31]
Ibus-Unikey hiện không gõ được từ "huơ" "khuơ"

**Comment by zenfas** [comment]
Hi @trmdi, bạn có thể hỗ trợ PR update các thay đổi gần đây trong năm nay trên fcitx5-unikey lên ibus-unikey được không? Mình cảm ơn nhé! Nếu bạn của thể tiếp quản domain này hỗ trợ Mr Tuấn thì tốt, do ibus-unikey đang được rất nhiều distro đưa vào repo chính.

**Comment by trmdi** [comment]
@zenfas 
Sorry, I only use KDE and fcitx5. For KDE, fcitx5 is the best. I don't care about other stuff. You or someone else are free to do that.

**Comment by tulequ** [comment]
Oh, I will do that when I have free time
Maybe soon!

Thank you, @trmdi
