### ISSUE TITLE
Change keyboard layout when using Ibus Unikey

### ISSUE THREAD

**Issue by thachpham92** [vn-input/ibus-unikey#4]
Hi,
I'm using Swedish keyboard with Nordic Swedish layout. Ibus Unikey only support qwerty US layout.
Then can I re-mapping ibus-unikey and where I can find settings file?

Thanks!

**Comment by cmpitg** [comment]
Hi,

I'm using both ibus-unikey and ibus-bogo with Programmer Dvorak layout for Finnish typing with no problem. Would you mind checking if you have enabled the *Use system keyboard layout* option in `ibus-setup`?

![Use system keyboard layout](http://i.imgur.com/Y3jfMwN.jpg)

Ha-Duong

**Comment by thachpham92** [comment]
Hi Ha,
Thanks for fast response!
I did take a look in 'ibus-setup' and set like below.

![2](https://cloud.githubusercontent.com/assets/3521898/10677334/f790bac4-790b-11e5-9496-a4276b0f7037.jpg)
![1](https://cloud.githubusercontent.com/assets/3521898/10677333/f7909c1a-790b-11e5-8c13-bf8c6d846df9.jpg)

Then I reboot my machine but nothing changes :(

**Comment by cmpitg** [comment]
Hi Thach,

You're welcome. What version of IBus and Ubuntu are you using?  Would you mind running the below commands in a terminal and pasting their outputs here?

```
lsb_release -a
apt-cache show ibus
apt-cache show libibus-1.0-5
```

In the meantime, please tryout ibus-unikey after running `ibus-daemon -xvr` to see if the IBus daemon has been correctly restarted and picked up the right setting.

Ha-Duong

**Comment by thachpham92** [comment]
Hi, I'm using Ubuntu 15.10. I may try out Ubuntu 14.04 LTS

```thachpham@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
thachpham@ubuntu:~$ apt-cache show ibus
Package: ibus
Priority: optional
Section: utils
Installed-Size: 1324
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: IME Packaging Team <pkg-ime-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 1.5.10-1ubuntu1
Depends: dconf-cli, gir1.2-gtk-3.0 (>= 3.8.5), gir1.2-ibus-1.0 (= 1.5.10-1ubuntu1), adwaita-icon-theme, librsvg2-common, python3-gi, dconf-gsettings-backend | gsettings-backend, python3:any (>= 3.3.2-2~), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.14), libcairo2 (>= 1.2.4), libdconf1 (>= 0.14.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk-3-0 (>= 3.7.0), libgtk2.0-0 (>= 2.24.5-4), libibus-1.0-5 (>= 1.5.5), libnotify4 (>= 0.7.0), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libx11-6, libxi6 (>= 2:1.2.99.4)
Recommends: ibus-gtk | ibus-qt4 | libqt5gui5, ibus-gtk3 | ibus-qt4 | libqt5gui5, im-config
Suggests: ibus-clutter, ibus-doc, ibus-qt4, libqt5gui5
Breaks: ibus-anthy (<< 1.5.3-2), ibus-el (<< 0.3.2-2), ibus-googlepinyin (<< 0.1.2-2)
Filename: pool/main/i/ibus/ibus_1.5.10-1ubuntu1_amd64.deb
Size: 200586
MD5sum: 0a852fe175a782a732c12cec40279410
SHA1: d772eb2d48add21615a18ea874967c51effcd574
SHA256: 176bfebfa80ed5231aa5b886dfb92f0298dd48f660ff899959ba458d0901f6ad
Description-en: Intelligent Input Bus - core
 IBus is an Intelligent Input Bus. It is a new input framework for the Linux
 OS. It provides full featured and user friendly input method user interface.
 It also may help developers to develop input method easily.
Description-md5: 489faf3b419b10c90a2fd62eb552cc93
Multi-Arch: foreign
Homepage: https://github.com/ibus/ibus/releases
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
Task: ubuntu-desktop, ubuntu-usb, edubuntu-desktop, edubuntu-usb, ubuntu-gnome-desktop, ubuntu-desktop-next, ubuntukylin-desktop

thachpham@ubuntu:~$ apt-cache show libibus-1.0-5
Package: libibus-1.0-5
Priority: optional
Section: libs
Installed-Size: 456
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: IME Packaging Team <pkg-ime-devel@lists.alioth.debian.org>
Architecture: amd64
Source: ibus
Version: 1.5.10-1ubuntu1
Depends: libc6 (>= 2.4), libglib2.0-0 (>= 2.37.3)
Filename: pool/main/i/ibus/libibus-1.0-5_1.5.10-1ubuntu1_amd64.deb
Size: 115586
MD5sum: e56ace51c15083c9bc6b09b69822c029
SHA1: 280279c763106ba304ee3135f29d932bf00cc5e9
SHA256: d67b6b165ee679941a40edd80bc7dab4f09873765090f5138a12aa779139891a
Description-en: Intelligent Input Bus - shared library
 IBus is an Intelligent Input Bus. It is a new input framework for the Linux
 OS. It provides full featured and user friendly input method user interface.
 It also may help developers to develop input method easily.
 .
 This package contains shared library
Description-md5: fb7cfdef40194dc7d14444000e952d91
Multi-Arch: same
Homepage: https://github.com/ibus/ibus/releases
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
Task: ubuntu-desktop, ubuntu-usb, kubuntu-desktop, kubuntu-full, edubuntu-desktop, edubuntu-usb, ubuntu-gnome-desktop, ubuntu-desktop-next, ubuntu-sdk, ubuntukylin-desktop, ubuntu-mate-live

thachpham@ubuntu:~$ ibus-daemon -xvr

(ibus-ui-gtk3:2627): IBUS-WARNING **: panel.vala:211: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:2627): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
```

**Comment by cmpitg** [comment]
Hi,

I don't have Ubuntu 15.10 so I cannot tell from my side. I'll install and try it tomorrow then.

Ha-Duong

**Comment by thachpham92** [comment]
Thanks cmpitg!
It seem working with ibus-bogo. But I hope can use ibus-unikey soon.

**Comment by duongphuhiep** [comment]
Any news? I'm in French, keyboard is AZERTY, nhưng khi chuyển sang ibus-unikey lại phải dùng QWERTY layout..

**Comment by duongphuhiep** [comment]
Here my hack to use `ibus-unikey` on a **French keyboard**

http://askubuntu.com/a/719585/77317

**Comment by cmpitg** [comment]
Sorry I forgot to check with Ubuntu 15.10 but apparently people are having [the same problem](https://github.com/BoGoEngine/ibus-bogo/issues/235) as well.  I think it's due to the fact that iBus no longer respects system keyboard layout set by some desktop environments on X11.

@duongphuhiep: Another workaround is to use `setxkbmap fr` to change keyboard layout to AZERTY. This has an advantage of being simple to reuse, manage, and make consistent.  [See the other issue for more information](https://github.com/BoGoEngine/ibus-bogo/issues/235#issuecomment-167957630).

Ha-Duong

**Comment by lewtds** [comment]
Mọi người thử patch file `/usr/share/ibus/component/unikey.xml` theo hướng dẫn này xem.

https://github.com/Ubuntu-VN/wiki/wiki/G%C3%B5-ti%E1%BA%BFng-Vi%E1%BB%87t#b%C3%A0n-ph%C3%ADm-dvorak-hay-colemak

**Comment by thanhphu** [comment]
> Mọi người thử patch file `/usr/share/ibus/component/unikey.xml` theo hướng dẫn này xem.
> 
> https://github.com/Ubuntu-VN/wiki/wiki/G%C3%B5-ti%E1%BA%BFng-Vi%E1%BB%87t#b%C3%A0n-ph%C3%ADm-dvorak-hay-colemak

Can confirm this works on ubuntu 18.04. Why is this not the default I don't know
